language: go

go:
    - 1.8
    - tip
before_install:
    - go get github.com/mattn/goveralls
    - go get golang.org/x/tools/cmd/cover

script:
    - go test -covermode=count -coverprofile=cover.out 
    - $HOME/gopath/bin/goveralls -service=travis-ci -coverprofile=cover.out
